language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lynuslyell/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lynuslyell/react-test npm run test

after_success:
  - docker build -t lynuslyell/multi-client ./client
  - docker build -t lynuslyell/multi-nginx ./nginx
  - docker build -t lynuslyell/multi-server ./server
  - docker build -t lynuslyell/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKERID" --password-stdin
  - docker push lynusevangelista/multi-client
  - docker push lynusevangelista/multi-nginx
  - docker push lynusevangelista/multi-server
  - docker push lynusevangelista/multi-worker